### ISSUE TITLE
Add plugin and for api 1.13.1 ( Genisys - php5 )

### ISSUE THREAD

**Issue by ghost** [MCrafterss/FlagSpiral#3]
Hello. You can add api and for php5 ? And plugin crash with"flag-time" error and unfillied 1 in FlagSpiralTask error for php5 ( i'm changed api to 1.13.1 )

**Comment by ghost** [comment]
And You can use this code by PEMAPMODDER pls ? 

$center = new Vector3(1, 1, 1);
$radius = 0.5;
$count = 100;
$particle = new WhateverParticle($center);
for($i = 0; $i < $count; $i++){
  $pitch = (mt_rand() / mt_getrandmax() - 0.5) \* M_PI;
  $yaw = mt_rand() / mt_getrandmax() \* 2 \* M_PI;
  $y = -sin($pitch);
  $delta = cos($pitch);
  $x = -sin($yaw) \* $delta;
  $z = cos($yaw) \* $delta;
  $v = new Vector3($x, $y, $z);
  $p = $center->add($v->normalize()->multiply($radius));
  $particle->setComponents($p->x, $p->y, $p->z);
  $level->addParticle($particle);
}

**Comment by Ragnok123** [comment]
FlagSpirals can not work in PHP5!

**Comment by Ragnok123** [comment]
Please, send me crashdump.

**Comment by ghost** [comment]
That's why the API 2.x.x update exists: Because it's Non-Backward-comptible with PHP 5.6.x. So that's impossible to add support for PHP 5.6 AND PHP 7.0.x.

**Comment by Taki21** [comment]
PHP5 Is Old...Please Update to PHP7 as this saves our time and all others' time...
