### ISSUE TITLE
Errors...

### ISSUE THREAD

**Issue by ghost** [MCrafterss/FlagSpiral#4]
1) Name file is CostumFlagSpiral , not CostumFlagSpiralTask ( photo )
2) Unfillied flag-time -> first creating resources file 
3) error glob-race ( photo ,spam console error , not functionable with error )

Genisys , php7.0.3 .
![screenshot_2016-04-27-00-56-55](https://cloud.githubusercontent.com/assets/13573011/14835612/47f580b8-0c13-11e6-9be0-9806cfac3d7d.png)
![screenshot_2016-04-27-00-56-08](https://cloud.githubusercontent.com/assets/13573011/14835622/53c5e36a-0c13-11e6-8290-4de5d4763221.png)

**Comment by xBeastMode** [comment]
This is late, but unfortunately, my plugins don't support genysis sorry, bye.
